import typer


def help():
    """Show full RacerAPI command list."""
    typer.echo("RacerAPI CLI Commands")
    typer.echo("")
    typer.echo("  new <name>           Create new project")
    typer.echo("  init                 Initialize in existing folder")
    typer.echo("  dev                  Start dev server")
    typer.echo("  start                Start production server")
    typer.echo("  build                Build project")
    typer.echo("  doctor               Diagnose project")
    typer.echo("  info                 Show project info")
    typer.echo("  --version            Show version")
    typer.echo("")
    typer.echo("AI Commands:")
    typer.echo("  ai create            AI-driven project creation")
    typer.echo("  ai generate module   AI module generator")
    typer.echo("  ai generate crud     AI CRUD generator")
    typer.echo("  ai docs              AI documentation")
    typer.echo("")
    typer.echo("Generators:")
    typer.echo("  generate resource    Resource module")
    typer.echo("  generate module      Module")
    typer.echo("  generate service     Service")
    typer.echo("  generate schema      Schema")
    typer.echo("  generate job         Job")
    typer.echo("")
    typer.echo("Tools:")
    typer.echo("  format               Format code")
    typer.echo("  lint                 Lint code")
    typer.echo("  test                 Run tests")
    typer.echo("  typecheck            Static type analysis")
